title: Rubin Hood
description: Minimalistischer Jekyll-Blog
baseurl: "/rubinhood-blog"
url: ""          # Das ist okay, solange baseurl gesetzt ist!
permalink: /:year/:month/:day/:title.html
theme: null
exclude: [Gemfile, Gemfile.lock, node_modules, vendor]

markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false

highlighter: rouge

paginate: 6                # Anzahl der Posts pro Seite (kannst du anpassen)
paginate_path: "/page:num" # URL-Pfad für weitere Seiten



